<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="einkaufslisteForm.aspx.cs" Inherits="PL_WGPlaner.einkaufslisteForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
     <link href="styling.css" rel="stylesheet" />
    <title>Einkaufsliste</title>
</head>

<body>
     <div id="content">
        <div id="logo"> 
            <img src="Bilder/logowg.png" width="250" >
        </div> 
        
    <form id="form1" runat="server">
        <div>
            <h1>Einkaufsliste</h1> 
            <h2> <asp:Label ID="lbl_GruppenName" runat="server" Text="GruppenName"></asp:Label></h2>
            <br />
            <asp:TextBox ID="txtbx_Artikel" placeholder="Artikel" runat="server" MaxLength="50"></asp:TextBox>
            <br />
            <asp:TextBox ID="txtbx_Anzahl" placeholder="Anzahl" runat="server" MaxLength="50" OnKeyPressed="txtbx_Anzahl_KeyPress"></asp:TextBox>
            <asp:TextBox ID="txtbx_Einheit" placeholder="Einheit" runat="server" MaxLength="50"></asp:TextBox>
            <br />
            <asp:Button ID="btn_AddItem" runat="server" Text="hinzufügen" OnClick="btn_AddItem_Click" />
            <br />
            <br />
            <div id="tabelle"> 
            <asp:GridView ID="grdvw_Einkaufslistenitems" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="EID" OnRowDeleting="grdvw_Einkaufslistenitems_RowDeleting">
                <Columns>
                    <asp:BoundField  DataField="Artikel" HeaderText="Artikel" />
                    <asp:BoundField  DataField="Anzahl" HeaderText="Anzahl" />
                    <asp:BoundField  DataField="Einheit" HeaderText="Einheit" />
                </Columns>
            </asp:GridView>
                </div>
            <br />
            <br />
            <nav>
            <asp:ImageButton ID="ImageButton1" runat="server" Height="50px" ImageUrl="Bilder/startseite.png" OnClick="ImageButton1_Click" Width="50px" />
            <asp:Label ID="lbl_HeutigerTag" runat="server" Text=""></asp:Label>
            <asp:Label ID="lbl_HeutigesDatum" runat="server" Text=""></asp:Label>
            <asp:ImageButton ID="ImageButton2" runat="server" Height="45px" ImageUrl="Bilder/benutzer.png" OnClick="ImageButton2_Click" Width="45px" />
                </nav>
        </div>
    </form>
         </div>
</body>
</html>
