<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mitgliederEinsehenForm.aspx.cs" Inherits="PL_WGPlaner.mitgliederEinsehenForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Mitglieder einsehen</title>
     <link href="styling.css" rel="stylesheet" />

</head>
<body>
     <div id="content"> 
    <div id="logo"> 
            <img src="Bilder/logowg.png" width="250" >
        </div> 

    <form id="form1" runat="server">
        <div>
            <asp:Button ID="btn_zurueck" runat="server" OnClick="btn_zurueck_Click" Text="Zurück" />
            <br />
            
            <h1>Mitglieder Einsehen </h1>
            
            <h3><asp:Label ID="lblGruppenName" runat="server" Text="GruppenName"></asp:Label> </h3>
            
            <div id="kalender"> 
            <asp:GridView ID="grdvw_Mitglieder" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" OnRowDeleting="grdvw_Mitglieder_RowDeleting" DataKeyNames="PID">
                <Columns>
                    <asp:BoundField  DataField="Benutzername" HeaderText="Personen" />
                </Columns>
            </asp:GridView>
                </div>
            <br />
            <br />
            <br />
            <br />
            <br />

            <nav> 
            <asp:ImageButton ID="ImageButton1" runat="server" Height="50px" ImageUrl="Bilder/startseite.png" OnClick="ImageButton1_Click" Width="50px" />
            <asp:Label ID="lbl_HeutigerTag" runat="server" Text=""></asp:Label>
            <asp:Label ID="lbl_HeutigesDatum" runat="server" Text=""></asp:Label>
            <asp:ImageButton ID="ImageButton2" runat="server" Height="45px" ImageUrl="Bilder/benutzer.png" OnClick="ImageButton2_Click" Width="45px" />

                </nav>
        </div>
    </form>
          </div>
</body>
</html>
